package pt.isec.br.TP_PA19_20.integration;

public enum  StateID {
    AWAIT_DICE_ROLL,
    AWAIT_MINING_CONFIRMATION,
    AWAIT_MOVEMENT,
    AWAIT_PLANET_DECISON,
    AWAIT_RESOURCES_CONVERSION,
    AWAIT_RESTART,
    AWAIT_SPACESHIP_SELECTION,
    AWAIT_SS_DECISION,
    GAME_OVER,
    LAST_CHANCE;
}
